[project]
name = "lazy-puzzle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "z3-solver>=4.15.4.0",
]

[dependency-groups]
dev = [
    "ipython>=9.10.0",
    "ruff>=0.15.0",
    "ty>=0.0.15",
]
